#cloud-config
#	
#	MIT License
#	
#	Copyright (c) 2024 Daniel-Doggy
#	
#	Permission is hereby granted, free of charge, to any person obtaining a copy
#	of this software and associated documentation files (the "Software"), to deal
#	in the Software without restriction, including without limitation the rights
#	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#	copies of the Software, and to permit persons to whom the Software is
#	furnished to do so, subject to the following conditions:
#	
#	The above copyright notice and this permission notice shall be included in all
#	copies or substantial portions of the Software.
#	
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#	SOFTWARE.

disable_root: true
ssh_pwauth: false
timezone: Europe/Berlin

users:
  - name: admin
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIACss3cEAow16htt4KyxzcQ9P4pZHTR7uJgSzOiOLXBI Yubikey - Primary
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHhimNIEqotLfqjACvjnokVvAgQfvz9BJEmlwoJSuHJZ Yubikey - Secondary
    sudo:  ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - qemu-guest-agent
  - git
  - fail2ban
  - dnsutils
  - certbot
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - git clone https://github.com/Daniel-Dog-dev/proxmox-ve-scripts.git
  - cd proxmox-ve-scripts/
  - mv ./files/Standard/jail-standard.local /etc/fail2ban/jail.local
  - systemctl restart fail2ban
  - chmod 755 ./files/Keycloak/install.sh
  - ./files/Keycloak/install.sh
  - cd ../
  - touch /etc/cloud/cloud-init.disabled